<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
if (function_exists('bp_is_current_component')) {
if(!bp_is_current_component( 'activity' ) && !bp_is_current_component( 'profile' ) && !bp_is_current_component( 'blogs' )
&& !bp_is_current_component( 'messages' ) && !bp_is_current_component( 'friends' ) && !bp_is_current_component( 'groups' )
&& !bp_is_current_component( 'settings' ) && !bp_is_current_component( 'notifications' ) && !bp_is_current_component( 'forums' ) && !is_bbpress()){

//* Output primary sidebar structure
genesis_markup( array(
	'html5'   => '<aside %s>',
	'xhtml'   => '<div id="sidebar" class="sidebar widget-area">',
	'context' => 'sidebar-primary',
) );

do_action( 'genesis_before_sidebar_widget_area' );
do_action( 'genesis_sidebar' );
do_action( 'genesis_after_sidebar_widget_area' );

genesis_markup( array(
	'html5' => '</aside>', //* end .sidebar-primary
	'xhtml' => '</div>', //* end #sidebar
) );
}
}